### ISSUE TITLE
Impossible to install python-lsp-isort on Python-3.12.1

### ISSUE THREAD

**Issue by parvizfarnia** [chantera/python-lsp-isort#3]
Hello

```
OS: Windows 11
Python version: 3.12.1 (64 bit)
Emacs version: 29.1

```

When I run in the terminal running my current virtual Python environment this command: `pip install python-lsp-isort` I get the following error message:

```
Collecting python-lsp-isort
  Using cached python-lsp-isort-0.1.tar.gz (3.8 kB)
  Installing build dependencies ... error
  error: subprocess-exited-with-error

  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [10 lines of output]
      WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x000001B270238680>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed')': /simple/setuptools/
      WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x000001B27033E0F0>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed')': /simple/setuptools/
      WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x000001B2705F3BF0>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed')': /simple/setuptools/
      WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x000001B2705F3C20>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed')': /simple/setuptools/
      WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x000001B2705F3E00>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed')': /simple/setuptools/
      ERROR: Could not find a version that satisfies the requirement setuptools (from versions: none)
      ERROR: No matching distribution found for setuptools

      [notice] A new release of pip is available: 23.2.1 -> 23.3.2
      [notice] To update, run: python.exe -m pip install --upgrade pip
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

I even installed setuptools via `pip install setuptools` as it is no more available by default in Python 3.12 but that didn't change anything.

Is there a way to install `python-lsp-isort` on Python 3.12.1 ?

Thanks in advance

**Comment by chantera** [comment]
As the error indicated `NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x000001B270238680>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed')`, there seemed to be a network problem, not a problem with pip or python-lsp-isort.
To figure out how to reproduce the error, could you try to install this package on a different version of Python or another package on the same version of Python?

**Comment by parvizfarnia** [comment]
As I indicated in my first comment, installation of `python-lsp-isort` failed in a `Python-3.12.1` virtual environment via `pip`. I tried to install it on a new virtual environment, but this time with the version 3.10.5. I can confirm the the same problem persists also using Python 3.10.5. Also, I checked that on both Python versions I was able to install other packages via pip.

**Comment by TheAnarchoX** [comment]
Same goes for python  python 3.10.12

```
$ pip install python-lsp-isort                                                                                                                                                                                                    [TheAnarchoOmen 09:50:11]
Defaulting to user installation because normal site-packages is not writeable
Collecting python-lsp-isort
  Using cached python-lsp-isort-0.1.tar.gz (3.8 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
  WARNING: Generating metadata for package python-lsp-isort produced metadata for project name unknown. Fix your #egg=python-lsp-isort fragments.
Discarding https://files.pythonhosted.org/packages/26/d1/30ae9c451f78da3f73cb3dbdfd9fe32055804a98bd2efe2b22d383ef3fe3/python-lsp-isort-0.1.tar.gz#sha256=f02948bc8e7549905032100e772f03464f7548afa96f07d744ff1f93cc58339a (from https://pypi.org/simple/python-lsp-isort/) (requires-python:>=3.7): Requested unknown from https://files.pythonhosted.org/packages/26/d1/30ae9c451f78da3f73cb3dbdfd9fe32055804a98bd2efe2b22d383ef3fe3/python-lsp-isort-0.1.tar.gz#sha256=f02948bc8e7549905032100e772f03464f7548afa96f07d744ff1f93cc58339a has inconsistent name: filename has 'python-lsp-isort', but metadata has 'unknown'
ERROR: Could not find a version that satisfies the requirement python-lsp-isort (from versions: 0.1)
ERROR: No matching distribution found for python-lsp-isort
```

**Comment by parvizfarnia** [comment]
Thanks for the information, it's rather reassuring that I am not alone in this. Therefore it seems that `python-lsp-isort` might not have been updated for compatibility with recent versions of Python. Nonetheless, it seems rather strange to me, given that almost everywhere when someone talks about LSP and Python, often this package is also mentioned. So I wonder how it comes that the issue has not been raised before, are we the only users so far, who have tried to install this on a recent Python version?

**Comment by chantera** [comment]
> I can confirm the the same problem persists also using Python 3.10.5. Also, I checked that on both Python versions I was able to install other packages via pip.

@parvizfarnia Thank you for checking installation.
In my environment, I could install `python-lsp-isort` both on Python 3.12 and 3.10.
The problem might be related to the Windows environment, which I haven't tested much.
Could you confirm that you can install it in another OS (such as Ubuntu using WSL)?

> Doesn't it have anything to do with setuptools?

Thank you for pointing out.
I will check it, but please give me some time.

**Comment by chantera** [comment]
@TheAnarchoX Thank you for reporting it. The issue looks different from the original one.
Could you tell me your OS and setuptools version?
I will try to reproduce it.

**Comment by TheAnarchoX** [comment]
Yes, its Ubuntu 18.02 on WSL 2, with setuptools 59.6.0

**Comment by parvizfarnia** [comment]
I have Ubuntu 22.04.1 installed on Oracle Virtualbox. On this system I have Python 3.11 and I managed to install isort, despite Deprecation warning messages:

```
$ python
Python 3.11.1 (main, Dec 24 2022, 00:54:02) [GCC 11.3.0] on linux

Type "help", "copyright", "credits" or "license" for more information.

>>> 
>>> 
>>> quit()
$ 
$ 
$ mkdir tmp_venv
$ cd tmp_venv
$ python -m venv .
$ source bin/activate
(tmp_venv) testusr@vbx:~/tmp_venv$ 
(tmp_venv) testusr@vbx:~/tmp_venv$ 
(tmp_venv) testusr@vbx:~/tmp_venv$ which python

/home/testusr/tmp_venv/bin/python

(tmp_venv) testusr@vbx:~/tmp_venv$ 
(tmp_venv) testusr@vbx:~/tmp_venv$ 
(tmp_venv) testusr@vbx:~/tmp_venv$ which pip

/home/testusr/tmp_venv/bin/pip

(tmp_venv) testusr@vbx:~/tmp_venv$ 
(tmp_venv) testusr@vbx:~/tmp_venv$ 
(tmp_venv) testusr@vbx:~/tmp_venv$ pip install python-lsp-isort
/home/testusr/tmp_venv/lib/python3.11/site-packages/pip/_vendor/packaging/version.py:111: DeprecationWarning: Creating a LegacyVersion has been deprecated and will be removed in the next major release

  warnings.warn(

Collecting python-lsp-isort
  Downloading python-lsp-isort-0.1.tar.gz (3.8 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting python-lsp-server
  Downloading python_lsp_server-1.9.0-py3-none-any.whl (75 kB)

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 75.5/75.5 kB 790.7 kB/s eta 0:00:00

Collecting isort>=5.0
  Downloading isort-5.13.2-py3-none-any.whl (92 kB)

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 92.3/92.3 kB 610.6 kB/s eta 0:00:00

Collecting docstring-to-markdown
  Downloading docstring_to_markdown-0.13-py3-none-any.whl (19 kB)

/home/testusr/tmp_venv/lib/python3.11/site-packages/pip/_vendor/packaging/version.py:111: DeprecationWarning: Creating a LegacyVersion has been deprecated and will be removed in the next major release

  warnings.warn(

Collecting jedi<0.20.0,>=0.17.2
  Downloading jedi-0.19.1-py2.py3-none-any.whl (1.6 MB)

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 691.0 kB/s eta 0:00:00

Collecting pluggy>=1.0.0
  Downloading pluggy-1.3.0-py3-none-any.whl (18 kB)

Collecting python-lsp-jsonrpc<2.0.0,>=1.1.0
  Downloading python_lsp_jsonrpc-1.1.2-py3-none-any.whl (8.8 kB)

Collecting ujson>=3.0.0
  Downloading ujson-5.9.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (53 kB)

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 53.2/53.2 kB 697.1 kB/s eta 0:00:00

Collecting parso<0.9.0,>=0.8.3
  Using cached parso-0.8.3-py2.py3-none-any.whl (100 kB)

Building wheels for collected packages: python-lsp-isort
  Building wheel for python-lsp-isort (pyproject.toml) ... done
  Created wheel for python-lsp-isort: filename=python_lsp_isort-0.1-py3-none-any.whl size=4337 sha256=f6daa404e8f3db47788a10c501935d6017b4f66aeaf8c4db02c57a1596ec7568

  Stored in directory: /home/testusr/.cache/pip/wheels/54/07/9b/78e0bb41e49e37f369186748a8b72630e6051808b7e354b069

Successfully built python-lsp-isort

Installing collected packages: ujson, pluggy, parso, isort, docstring-to-markdown, python-lsp-jsonrpc, jedi, python-lsp-server, python-lsp-isort

Successfully installed docstring-to-markdown-0.13 isort-5.13.2 jedi-0.19.1 parso-0.8.3 pluggy-1.3.0 python-lsp-isort-0.1 python-lsp-jsonrpc-1.1.2 python-lsp-server-1.9.0 ujson-5.9.0



[notice] A new release of pip available: 22.3.1 -> 23.3.2

[notice] To update, run: pip install --upgrade pip

(tmp_venv) testusr@vbx:~/tmp_venv$ 
```

**Comment by parvizfarnia** [comment]
Any more development on this topic given that the problem persists on Windows ?

**Comment by chantera** [comment]
I am willing to fix the problem, but currently cannot have a time to inspect it.
I think I would be available in April or May.
Sorry for the inconvenience, but I welcome your contribution to the OSS project.

**Comment by chantera** [comment]
I quickly took a look into the problem.
In my environment (Windows 11, Python 3.12.2), I successfully installed python-lsp-isort without any trouble.
So, I think the problem might be related to a network issue, as I told you before.
Could you try to install the package again?

![image](https://github.com/chantera/python-lsp-isort/assets/1482049/5a828a05-f8c5-486e-b2a7-d2107bbe45f1)

**Comment by chantera** [comment]
@TheAnarchoX I tried to reproduce the problem, but I couldn't find any problem.

```
~/work/tmp via py v3.10.6 (.venv)
> pip list
Package    Version
---------- -------
pip        22.0.2
setuptools 59.6.0

~/work/tmp via py v3.10.6 (.venv)
> pip install python-lsp-isort
Collecting python-lsp-isort
  Using cached python_lsp_isort-0.1-py3-none-any.whl
Collecting isort>=5.0
  Downloading isort-5.13.2-py3-none-any.whl (92 kB)
Collecting python-lsp-server
  Downloading python_lsp_server-1.10.0-py3-none-any.whl (75 kB)
Collecting docstring-to-markdown
  Downloading docstring_to_markdown-0.13-py3-none-any.whl (19 kB)
Collecting pluggy>=1.0.0
  Downloading pluggy-1.4.0-py3-none-any.whl (20 kB)
Collecting python-lsp-jsonrpc<2.0.0,>=1.1.0
  Downloading python_lsp_jsonrpc-1.1.2-py3-none-any.whl (8.8 kB)
Collecting jedi<0.20.0,>=0.17.2
  Downloading jedi-0.19.1-py2.py3-none-any.whl (1.6 MB)
Collecting ujson>=3.0.0
  Downloading ujson-5.9.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (53 kB)
Collecting parso<0.9.0,>=0.8.3
  Using cached parso-0.8.3-py2.py3-none-any.whl (100 kB)
Installing collected packages: ujson, pluggy, parso, isort, docstring-to-markdown, python-lsp-jsonrpc, jedi, python-lsp-server, python-lsp-isort
Successfully installed docstring-to-markdown-0.13 isort-5.13.2 jedi-0.19.1 parso-0.8.3 pluggy-1.4.0 python-lsp-isort-0.1 python-lsp-jsonrpc-1.1.2 python-lsp-server-1.10.0 ujson-5.9.0
```

If the problem still persists, could you open a new issue since it's different from the original one?

**Comment by parvizfarnia** [comment]
> I quickly took a look into the problem. In my environment (Windows 11, Python 3.12.2), I successfully installed python-lsp-isort without any trouble. So, I think the problem might be related to a network issue, as I told you before. Could you try to install the package again?
> 
> ![image](https://private-user-images.githubusercontent.com/1482049/303827454-5a828a05-f8c5-486e-b2a7-d2107bbe45f1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc3MjgwMjEsIm5iZiI6MTcwNzcyNzcyMSwicGF0aCI6Ii8xNDgyMDQ5LzMwMzgyNzQ1NC01YTgyOGEwNS1mOGM1LTQ4NmUtYjJhNy1kMjEwN2JiZTQ1ZjEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMTJUMDg0ODQxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODk0MzdjOTEzNDQzZjAyYzMzYjI3NWU2ZTA4ZjlhNjVhNzFlNWRmMzA3YTcyNDJmZDIzZWM2M2RjZjU3NTZiNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.yTIp7qXOR5miC6PqlKwMdc83iifvopaJOtfoC3vnT7g)

Thank you very much for your time.

I tried to reinstall isort once again, and I can confirm:

- The problem persists

- It seems to me that it has nothing to do with network, given that within the same virtual machin (Python 3.12.1), pip is able to download and install other packages.

As you mentioned in your comment, upon May or April, whenever you will be available, I'd be glad to have a follow-up on this topic.

Thank you.

**Comment by chantera** [comment]
@parvizfarnia Thank you for your understanding and cooperation.
Could you re-try installation with `pip install python-lsp-isort -vvv` and paste the output here?

**Comment by parvizfarnia** [comment]
Sure. Here is the output:


```
Using pip 23.2.1 from D:\MyPrograms\python_virtual_envs\3.12.1\Lib\site-packages\pip (python 3.12)
Non-user install because user site-packages disabled
Created temporary directory: C:\Users\myuser\AppData\Local\Temp\pip-build-tracker-k8839y4w
Initialized build tracking at C:\Users\myuser\AppData\Local\Temp\pip-build-tracker-k8839y4w
Created build tracker: C:\Users\myuser\AppData\Local\Temp\pip-build-tracker-k8839y4w
Entered build tracker: C:\Users\myuser\AppData\Local\Temp\pip-build-tracker-k8839y4w
Created temporary directory: C:\Users\myuser\AppData\Local\Temp\pip-install-9vd6ppyx
Created temporary directory: C:\Users\myuser\AppData\Local\Temp\pip-ephem-wheel-cache-wou9pz4h
1 location(s) to search for versions of python-lsp-isort:
* https://pypi.org/simple/python-lsp-isort/
Fetching project page and analyzing links: https://pypi.org/simple/python-lsp-isort/
Getting page https://pypi.org/simple/python-lsp-isort/
Found index url https://pypi.org/simple/
Looking up "https://pypi.org/simple/python-lsp-isort/" in the cache
Request header has "max_age" as 0, cache bypassed
Starting new HTTPS connection (1): pypi.org:443
https://pypi.org:443 "GET /simple/python-lsp-isort/ HTTP/1.1" 304 0
Fetched page https://pypi.org/simple/python-lsp-isort/ as application/vnd.pypi.simple.v1+json
  Found link https://files.pythonhosted.org/packages/26/d1/30ae9c451f78da3f73cb3dbdfd9fe32055804a98bd2efe2b22d383ef3fe3/python-lsp-isort-0.1.tar.gz (from https://pypi.org/simple/python-lsp-isort/) (requires-python:>=3.7), version: 0.1
Skipping link: not a file: https://pypi.org/simple/python-lsp-isort/
Given no hashes to check 1 links for project 'python-lsp-isort': discarding no candidates
Collecting python-lsp-isort
  Created temporary directory: C:\Users\myuser\AppData\Local\Temp\pip-unpack-zy4ev9_x
  Looking up "https://files.pythonhosted.org/packages/26/d1/30ae9c451f78da3f73cb3dbdfd9fe32055804a98bd2efe2b22d383ef3fe3/python-lsp-isort-0.1.tar.gz" in the cache
  Current age based on date: 3009125
  Ignoring unknown cache-control directive: immutable
  Freshness lifetime from max-age: 365000000
  The response is "fresh", returning cached response
  365000000 > 3009125
  Using cached python-lsp-isort-0.1.tar.gz (3.8 kB)
  Added python-lsp-isort from https://files.pythonhosted.org/packages/26/d1/30ae9c451f78da3f73cb3dbdfd9fe32055804a98bd2efe2b22d383ef3fe3/python-lsp-isort-0.1.tar.gz to build tracker 'C:\\Users\\myuser\\AppData\\Local\\Temp\\pip-build-tracker-k8839y4w'
  Created temporary directory: C:\Users\myuser\AppData\Local\Temp\pip-build-env-ih4jdtps
  Running command pip subprocess to install build dependencies
  Using pip 23.2.1 from D:\MyPrograms\python_virtual_envs\3.12.1\Lib\site-packages\pip (python 3.12)
  WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x000001A61154BA10>: Failed to establish a new connection: [WinError 10013] Une tentative d’accès à un socket de manière interdite par ses autorisations d’accès a été tentée')': /simple/setuptools/
  WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x000001A61166E180>: Failed to establish a new connection: [WinError 10013] Une tentative d’accès à un socket de manière interdite par ses autorisations d’accès a été tentée')': /simple/setuptools/
  WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x000001A61166E390>: Failed to establish a new connection: [WinError 10013] Une tentative d’accès à un socket de manière interdite par ses autorisations d’accès a été tentée')': /simple/setuptools/
  WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x000001A61166E570>: Failed to establish a new connection: [WinError 10013] Une tentative d’accès à un socket de manière interdite par ses autorisations d’accès a été tentée')': /simple/setuptools/
  WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x000001A61166E720>: Failed to establish a new connection: [WinError 10013] Une tentative d’accès à un socket de manière interdite par ses autorisations d’accès a été tentée')': /simple/setuptools/
  ERROR: Could not find a version that satisfies the requirement setuptools (from versions: none)
  ERROR: No matching distribution found for setuptools

  [notice] A new release of pip is available: 23.2.1 -> 24.0
  [notice] To update, run: python.exe -m pip install --upgrade pip
  error: subprocess-exited-with-error

  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: 'D:\MyPrograms\python_virtual_envs\3.12.1\Scripts\python.exe' 'D:\MyPrograms\python_virtual_envs\3.12.1\Lib\site-packages\pip\__pip-runner__.py' install --ignore-installed --no-user --prefix 'C:\Users\myuser\AppData\Local\Temp\pip-build-env-ih4jdtps\overlay' --no-warn-script-location -v --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools
  cwd: [inherit]
  Installing build dependencies ... error
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
Exception information:
Traceback (most recent call last):
  File "D:\MyPrograms\python_virtual_envs\3.12.1\Lib\site-packages\pip\_internal\cli\base_command.py", line 180, in exc_logging_wrapper
    status = run_func(*args)
             ^^^^^^^^^^^^^^^
  File "D:\MyPrograms\python_virtual_envs\3.12.1\Lib\site-packages\pip\_internal\cli\req_command.py", line 248, in wrapper
    return func(self, options, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\MyPrograms\python_virtual_envs\3.12.1\Lib\site-packages\pip\_internal\commands\install.py", line 377, in run
    requirement_set = resolver.resolve(
                      ^^^^^^^^^^^^^^^^^
  File "D:\MyPrograms\python_virtual_envs\3.12.1\Lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 92, in resolve
    result = self._result = resolver.resolve(
                            ^^^^^^^^^^^^^^^^^
  File "D:\MyPrograms\python_virtual_envs\3.12.1\Lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 546, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\MyPrograms\python_virtual_envs\3.12.1\Lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 397, in resolve
    self._add_to_criteria(self.state.criteria, r, parent=None)
  File "D:\MyPrograms\python_virtual_envs\3.12.1\Lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 173, in _add_to_criteria
    if not criterion.candidates:
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\MyPrograms\python_virtual_envs\3.12.1\Lib\site-packages\pip\_vendor\resolvelib\structs.py", line 156, in __bool__
    return bool(self._sequence)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\MyPrograms\python_virtual_envs\3.12.1\Lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 155, in __bool__
    return any(self)
           ^^^^^^^^^
  File "D:\MyPrograms\python_virtual_envs\3.12.1\Lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 143, in <genexpr>
    return (c for c in iterator if id(c) not in self._incompatible_ids)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\MyPrograms\python_virtual_envs\3.12.1\Lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 47, in _iter_built
    candidate = func()
                ^^^^^^
  File "D:\MyPrograms\python_virtual_envs\3.12.1\Lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 206, in _make_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
                                       ^^^^^^^^^^^^^^
  File "D:\MyPrograms\python_virtual_envs\3.12.1\Lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 293, in __init__
    super().__init__(
  File "D:\MyPrograms\python_virtual_envs\3.12.1\Lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 156, in __init__
    self.dist = self._prepare()
                ^^^^^^^^^^^^^^^
  File "D:\MyPrograms\python_virtual_envs\3.12.1\Lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 225, in _prepare
    dist = self._prepare_distribution()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\MyPrograms\python_virtual_envs\3.12.1\Lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 304, in _prepare_distribution
    return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\MyPrograms\python_virtual_envs\3.12.1\Lib\site-packages\pip\_internal\operations\prepare.py", line 538, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\MyPrograms\python_virtual_envs\3.12.1\Lib\site-packages\pip\_internal\operations\prepare.py", line 653, in _prepare_linked_requirement
    dist = _get_prepared_distribution(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\MyPrograms\python_virtual_envs\3.12.1\Lib\site-packages\pip\_internal\operations\prepare.py", line 69, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(
  File "D:\MyPrograms\python_virtual_envs\3.12.1\Lib\site-packages\pip\_internal\distributions\sdist.py", line 38, in prepare_distribution_metadata
    self._prepare_build_backend(finder)
  File "D:\MyPrograms\python_virtual_envs\3.12.1\Lib\site-packages\pip\_internal\distributions\sdist.py", line 70, in _prepare_build_backend
    self.req.build_env.install_requirements(
  File "D:\MyPrograms\python_virtual_envs\3.12.1\Lib\site-packages\pip\_internal\build_env.py", line 217, in install_requirements
    self._install_requirements(
  File "D:\MyPrograms\python_virtual_envs\3.12.1\Lib\site-packages\pip\_internal\build_env.py", line 275, in _install_requirements
    call_subprocess(
  File "D:\MyPrograms\python_virtual_envs\3.12.1\Lib\site-packages\pip\_internal\utils\subprocess.py", line 224, in call_subprocess
    raise error
pip._internal.exceptions.InstallationSubprocessError: pip subprocess to install build dependencies exited with 1
Remote version of pip: 24.0
Local version of pip:  23.2.1
Was pip installed by pip? True

[notice] A new release of pip is available: 23.2.1 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip
Removed python-lsp-isort from https://files.pythonhosted.org/packages/26/d1/30ae9c451f78da3f73cb3dbdfd9fe32055804a98bd2efe2b22d383ef3fe3/python-lsp-isort-0.1.tar.gz from build tracker 'C:\\Users\\myuser\\AppData\\Local\\Temp\\pip-build-tracker-k8839y4w'
Removed build tracker: 'C:\\Users\\myuser\\AppData\\Local\\Temp\\pip-build-tracker-k8839y4w'

(3.12.1) D:\tmp>
```
